### PR TITLE
Add section on device-mapper naming

### PR DESCRIPTION
**Pull request by agrover**
Hi, here's a take on documenting and standardizing our dm names. GitHub isn't great for reviewing changes to LyX docs... let me know if this works or if you'd prefer I just apply draft text and then review a pdf.

### CODE REVIEW

**Comment by agrover** [comment]
[Rendered](https://fedorapeople.org/~grover/StratisSoftwareDesign.pdf)

**Comment by agrover** [comment]
moving back to review-prelim, aside from the content I can see there are some formatting issues to resolve.

**Comment by mulkieran** [comment]
Maybe you should leave out "This is also import...reboot." sentence. It had me confused for a while.

```stratis-version``` might be better as ```format-version```.

Each example might be better as a one-element description list.

We should write some code to support this naming scheme. Should be relatively simple, but will save trouble later.

**Comment by agrover** [comment]
> We should write some code to support this naming scheme. Should be relatively simple, but will save trouble later.

What sort of code?

**Comment by agrover** [comment]
* Removed sentence about reboot
* Renamed `stratis-version` to `format-version`
* Used Description for examples

**Comment by mulkieran** [comment]
We need code to support correctly and consistently extracting the correct data from the name. So, we might as well have corresponding code to generate the name at some point. And run some quickcheck tests on it, so that we don't get caught by some stupid formatting error, (which would cause all of setup to fail).

**Comment by agrover** [comment]
A function to help build the names does seem nice (opened a bug). Surprisingly, I don't currently see a use case for ever parsing these, but if we ever did then naturally I agree we'd want to ensure correctness.

**Comment by agrover** [comment]
@mulkieran any last comments or is this PR good to go?

**Comment by trgill** [comment]
👍

**Pull request merged**
