### PR TITLE
Update for optional addition of 'private' to DM names

### LINKED ISSUE #80: update design doc dm name spec for new "private" substring
see https://github.com/stratis-storage/stratisd/pull/814

### PR DESCRIPTION
**Pull request by agrover**
fixes #80

Signed-off-by: Andy Grover <agrover@redhat.com>

### CODE REVIEW

**Comment by agrover** [comment]
screenshot from 2018-06-14 10-57-14

**Comment by mulkieran** [comment]
Suggestions:

"private-id" -> "private" in Name column.
"private-id" -> "\"private\"" in bullet points

"Stratis DM names ..." ->
  "Stratis DM names consist of five required and two optional parts, separated by a '-'."

Omit last bullet point. If it is a DM constraint, then we must obey it, and we don't really have to describe it. If it's not a DM constraint, then we shouldn't impose it on ourselves. Or it could be described as a DM constraint.

* devicemapper restrictions for devicemapper names, i.e., <those restrictions>, are obeyed.

**Comment by mulkieran** [comment]
"each separated" -> "separated". This way the parts are separated from each other. If each is separated by a dash, the meaning is that the parts are broken up, somehow.

**Comment by mulkieran** [comment]
"The maximum length..." -> 
  The maximum name length is 125 characters, less than the DM name limit of 127 characters."

"Character limitations..." ->
  "Characters for each part must be drawn solely from the character classes '[a-z]' and '[0-9]' except that part 7 may also use the '-' character. These restrictions meet D-Bus and udev requirements```footnote here```.

**Comment by agrover** [comment]
adopted suggestions 1 and 3, wasn't totally digging 2 so I took another stab at wording.

**Pull request merged**
