### PR TITLE
Master ref changes

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by mulkieran** [comment]
I believe this more or less resolves #23.

**Comment by agrover** [comment]
Yup, just one little nit: I like how it references the stratisd version it applies to, I think it also needs its own, independent version number as well.

**Comment by mulkieran** [comment]
When will it change its own version?

**Comment by agrover** [comment]
Up to the doc owner (you) but typically < 1.0 leading up to being done/released, completed version is 1.0, and then bump major or minor version as needed for further updates. It primarily helps for keeping review comments straight, and also decouples the implementation version from the API version, which is desirable.

**Comment by mulkieran** [comment]
Ok, I've edited the title page a bit, to show the document version along with the last updated date.

**Comment by mulkieran** [comment]
I also added a pointer in the design doc to the now existing reference doc.

**Comment by agrover** [comment]
did we lose last modified date accidentally?

**Comment by mulkieran** [comment]
It is still there, but now it's correct!

**Comment by agrover** [comment]
oh, ok. 👍

**Comment by mulkieran** [comment]
Just fixed a missing "s". merging soon.

**Pull request merged**
