### PR TITLE
Add a References section to Stratis design doc

### PR DESCRIPTION
**Pull request by mulkieran**
Resolves: #11.

### CODE REVIEW

**Comment by mulkieran** [comment]
@agrover review?

**Comment by agrover** [comment]
references meaning libs stratis (aka stratis-cli) or stratisd depend on?

**Comment by mulkieran** [comment]
References meaning things we might refer to about general principles when constructing the various parts of Stratis.

**Comment by mulkieran** [comment]
Plan to put something like this in the CLI doc, instead.

**Comment by mulkieran** [comment]
@agrover review?

**Comment by agrover** [comment]
👍

**Pull request merged**
