### PR TITLE
Add state transitions for daemon, pool, and pool space

### PR DESCRIPTION
**Pull request by agrover**
Signed-off-by: Andy Grover <agrover@redhat.com>

### CODE REVIEW

**Comment by agrover** [comment]
screenshot from 2018-06-13 09-13-31

**Comment by mulkieran** [comment]
"Running (or terminate)" is a wierd expression.

Basically, that we should acknowledge the possibility of things being in different states is good. I can't say whether I think these are the correct ones.

Using dot to make a diagram of transitions would be nice.

**Comment by agrover** [comment]
> "Running (or terminate)" is a wierd expression.

I was trying to express that if stratisd is killed that's something that can happen but doesn't make sense as a state that stratisd itself tracks. Similar to there being no pool state if Initialization fails -- there's no pool to have a state for.

> Basically, that we should acknowledge the possibility of things being in different states is good. I can't say whether I think these are the correct ones.

That's kind of what I'm looking for, or at least that these are adequate for an initial implementation, and then we can iterate.

> Using dot to make a diagram of transitions would be nice.

Yeah I'll likely do this once the states firm up a bit.

**Comment by agrover** [comment]
Hi @trgill I'm going to transfer this to you, since you are taking on the state transition stuff.

**Comment by agrover** [comment]
fixed by #105

**Pull request closed without merging**
