### PR TITLE
Extend top-level clean to recursively clean directories

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by mulkieran** [comment]
Sigh, tidy doesn't come for free.

**Comment by mulkieran** [comment]
I have spent almost all the energy I'm prepared to on auto-validating a single HTML file. I tried html5validator, but it had problems installing because the version of Python was too old. Specifying more modern version of Python in .travis.yml and seeing if that succeeds. I also tried the venerable tidy, but the version on Travis is from 2009, which means something.

**Comment by mulkieran** [comment]
rebased. Should pass tests.

**Comment by agrover** [comment]
I like the Makefile updates, but the work here to validate the html makes me wonder if we shouldn't just generate it from Markdown like our other static pages? But if you want to merge this thats :+1: with me, too.

**Comment by mulkieran** [comment]
Ok. I'll try that in a separate P

> I like the Makefile updates, but the work here to validate the html makes me wonder if we shouldn't just generate index.html from Markdown like our other static pages? But if you want to merge this thats +1 with me, too.

Ok. I'll try that in a separate PR.

**Comment by mulkieran** [comment]
With just the makefile changes it qualifies as trivial.

**Comment by mulkieran** [comment]
Removed commit:

```
commit eb71b79ebb28f4441f4246b07124381e8f5038a3 (HEAD -> master-tidy-save)
Author: mulhern <amulhern@redhat.com>
Date:   Fri Nov 16 10:45:23 2018 -0500

    Use html5validator to validate index.html
    
    Because it is easy to use on Travis and the version of tidy available
    on Travis is old.
    
    Signed-off-by: mulhern <amulhern@redhat.com>

diff --git a/.travis.yml b/.travis.yml
index 838a91d..c6ee19a 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,3 +1,14 @@
+language: python
+python: "3.5"
+
+addons:
+  apt:
+    packages:
+      - openjdk-8-jre
+
+install:
+  - pip install html5validator
+
 branches:
   only:
     - master
diff --git a/Makefile b/Makefile
index c5a1ad9..fd5437b 100644
--- a/Makefile
+++ b/Makefile
@@ -22,6 +22,7 @@ check:
        cd ./docs/design ; $(MAKE) check && cd -
        cd ./docs/dbus ; $(MAKE) check && cd -
        cd ./docs/style ; $(MAKE) check && cd -
+       cd ./website ; $(MAKE) check && cd -
 
 clean:
        - rm -Rf $(SITE)
diff --git a/website/Makefile b/website/Makefile
new file mode 100644
index 0000000..668a320
--- /dev/null
+++ b/website/Makefile
@@ -0,0 +1,2 @@
+check:
+       html5validator index.html
```

**Pull request merged**
