### PR TITLE
Ssg zola

### PR DESCRIPTION
**Pull request by kbknapp**
Implements stratis-storage/stratis-storage.github.io#2

There's details about how everything fits together in the README.rst. The biggest difference is the location of the relnotes and faq/howto markdow files has changed.

The primary Makefile still handles everything, but also now includes a test to make sure the `zola` and `lyx` binaries exist.

### CODE REVIEW

**Comment by kbknapp** [comment]
Yeah that'd be entirely possible! I'll add that when I get home from work today and push the commit.

**Comment by mulkieran** [comment]
Thanks, much appreciated!

**Comment by kbknapp** [comment]
I can squash all these commits into a single one when I get home tonight :wink:

**Comment by mulkieran** [comment]
Thanks!

**Comment by mulkieran** [comment]
I kept getting the angry pink unicorn symbol when I hit the "Approve" button, I didn't realize it was going in.

**Pull request merged**
